name: update-flake-lock
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 5"

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@V28
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@main
        with:
          pr-title: "flake: update the lock" # Title of PR to be created
          pr-labels: | # Labels to be set on the PR
            dependencies
            automated
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: peter-evans/enable-pull-request-automerge@v3
        with:
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: squash
